@base_address = http://localhost:5285/api/users

//Requirement in the specification
POST {{base_address}}
Content-Type: application/json

{
  "name": "name6"
}

//Requirement in the specification
###
GET {{base_address}}

//Requirement in the specification
###
GET {{base_address}}/3

//Requirement in the specification
###
PUT {{base_address}}/3
Content-Type: application/json

{
    "id":3,
    "name": "h"
}

//Requirement in the specification
###
DELETE {{base_address}}/3

