@base_address = http://localhost:5285/api/users

//Requirement in the specification
POST {{base_address}}
Content-Type: application/json

{
  "name": "name6"
}

//Requirement in the specification
###
GET {{base_address}}

//Requirement in the specification
###
GET {{base_address}}/1

//Requirement in the specification
###
PUT {{base_address}}/4
Content-Type: application/json

{

    "id":"4",
    "name": "h",
    "email": "1@h",
    "phone": "123"
}

//Requirement in the specification
###
DELETE {{base_address}}/9

