@base_address = http://localhost:5285/api/users

POST {{base_address}}
Content-Type: application/json

{
  "name": "name6"
}

###
GET {{base_address}}

###
GET {{base_address}}/3

###
PUT {{base_address}}/3
Content-Type: application/json

{
    "id":3,
    "name": "h"
}
